POST http://localhost:8080/api/v1/item/add
Content-Type: application/json

{
  "login": "vldr2",
  "password": "password",
  "wordCoder": "password",
  "email": "vldr2@gmail.com",
  "firstName": "Volodya",
  "INN": "abc",
  "lastName": "Vladimir",
  "fullNameCompany": "Unknown",
  "typeSubject": "",
  "organizationalForm": ""
}

###
GET http://localhost:8080/api/v1/item/users

DELETE http://localhost:8080/api/v1/item/1